- .azure-pipelines/azure-pipelines-linux.yml
- .azure-pipelines/azure-pipelines-osx.yml
- .ci_support/linux_python2.7.yaml
- .ci_support/linux_python3.6.yaml
- .ci_support/linux_python3.7.yaml
- .ci_support/osx_python2.7.yaml
- .ci_support/osx_python3.6.yaml
- .ci_support/osx_python3.7.yaml
- README.md
- recipe/build.sh
- recipe/meta.yaml
> Enable Python bindings

- README.md
- recipe/meta.yaml
> Fix runtime dependencies

- recipe/meta.yaml
- recipe/patches/core-remove-useless-include.patch
> patch version 1.4.6

- recipe/meta.yaml
> Rebuild against eigenpy 1.4.4

- .azure-pipelines/azure-pipelines-linux.yml
- .ci_support/linux_64_boost1.72.0python3.6.____cpython.yaml
- .ci_support/linux_64_boost1.72.0python3.7.____cpython.yaml
- .ci_support/linux_64_boost1.72.0python3.8.____cpython.yaml
- .ci_support/linux_64_boost1.72.0python3.9.____cpython.yaml
- .ci_support/linux_64_boost1.74.0python3.6.____cpython.yaml
- .ci_support/linux_64_boost1.74.0python3.7.____cpython.yaml
- .ci_support/linux_64_boost1.74.0python3.8.____cpython.yaml
- .ci_support/linux_64_boost1.74.0python3.9.____cpython.yaml
- recipe/build.sh
- recipe/meta.yaml
> Add support for Python doc

- .ci_support/linux_64_boost1.72.0python3.6.____cpython.yaml
- .ci_support/linux_64_boost1.72.0python3.7.____cpython.yaml
- .ci_support/linux_64_boost1.72.0python3.8.____cpython.yaml
- .ci_support/linux_64_boost1.72.0python3.9.____cpython.yaml
- .ci_support/linux_64_boost1.74.0python3.6.____cpython.yaml
- .ci_support/linux_64_boost1.74.0python3.7.____cpython.yaml
- .ci_support/linux_64_boost1.74.0python3.8.____cpython.yaml
- .ci_support/linux_64_boost1.74.0python3.9.____cpython.yaml
- .ci_support/osx_64_boost1.72.0python3.6.____cpython.yaml
- .ci_support/osx_64_boost1.72.0python3.7.____cpython.yaml
- .ci_support/osx_64_boost1.72.0python3.8.____cpython.yaml
- .ci_support/osx_64_boost1.72.0python3.9.____cpython.yaml
- .ci_support/osx_64_boost1.74.0python3.6.____cpython.yaml
- .ci_support/osx_64_boost1.74.0python3.7.____cpython.yaml
- .ci_support/osx_64_boost1.74.0python3.8.____cpython.yaml
- .ci_support/osx_64_boost1.74.0python3.9.____cpython.yaml
- recipe/meta.yaml
> rebuild for Eigen 3.3.9

- .azure-pipelines/azure-pipelines-osx.yml
- .ci_support/osx_arm64_python3.8.____cpython.yaml
- .ci_support/osx_arm64_python3.9.____cpython.yaml
- .scripts/build_steps.sh
- .scripts/run_osx_build.sh
- README.md
- conda-forge.yml
- recipe/build.sh
- recipe/meta.yaml
> Enable osx-arm64

- recipe/build.sh
- recipe/meta.yaml
> Fix sed command

- recipe/meta.yaml
- recipe/patches/all.patch
> recipe: add more patch

- .ci_support/osx_64_numpy1.19python3.7.____73_pypy.yaml
- .ci_support/osx_64_numpy1.19python3.7.____cpython.yaml
- .ci_support/osx_64_numpy1.19python3.8.____cpython.yaml
- .ci_support/osx_64_numpy1.19python3.9.____cpython.yaml
- .ci_support/osx_64_numpy1.21python3.10.____cpython.yaml
- .ci_support/osx_arm64_numpy1.19python3.8.____cpython.yaml
- .ci_support/osx_arm64_numpy1.19python3.9.____cpython.yaml
- .ci_support/osx_arm64_numpy1.21python3.10.____cpython.yaml
- recipe/meta.yaml
> rebuild for EigenPy >= 2.7.4

- recipe/meta.yaml
> Sync with latest eigenpy

- .github/CODEOWNERS
- README.md
- conda-forge.yml
- recipe/meta.yaml
> Be also a maintainer for hpp-fcl to maintain v1 abi branch for hpp-xxx stack

- .ci_support/migrations/assimp524.yaml
- .github/CODEOWNERS
- README.md
- recipe/meta.yaml
> regenerate

- .ci_support/osx_arm64_numpy1.20python3.8.____cpython.yaml
- .ci_support/osx_arm64_numpy1.20python3.9.____cpython.yaml
- .ci_support/osx_arm64_numpy1.21python3.10.____cpython.yaml
- recipe/conda_build_config.yaml
- recipe/meta.yaml
> Fix potential M1 issue with boost-python

- .ci_support/migrations/assimp525.yaml
- recipe/meta.yaml
> rebuild for eigenpy 2.9.1

- recipe/meta.yaml
> sync with eigenpy 2.9.2

- .github/CODEOWNERS
- .scripts/build_steps.sh
- .scripts/run_osx_build.sh
- .scripts/run_win_build.bat
- README.md
- build-locally.py
- recipe/meta.yaml
> Sync with latest eigenpy version

- recipe/meta.yaml
> sync for latest eigenpy

- recipe/meta.yaml
> Rebuild for latest EigenPy

- .ci_support/osx_64_numpy2.0python3.10.____cpython.yaml
- .ci_support/osx_64_numpy2.0python3.11.____cpython.yaml
- .ci_support/osx_64_numpy2.0python3.12.____cpython.yaml
- .ci_support/osx_64_numpy2.0python3.9.____cpython.yaml
- .ci_support/osx_64_numpy2python3.13.____cp313.yaml
- .ci_support/osx_arm64_numpy2.0python3.10.____cpython.yaml
- .ci_support/osx_arm64_numpy2.0python3.11.____cpython.yaml
- .ci_support/osx_arm64_numpy2.0python3.12.____cpython.yaml
- .ci_support/osx_arm64_numpy2.0python3.9.____cpython.yaml
- .ci_support/osx_arm64_numpy2python3.13.____cp313.yaml
- .scripts/run_win_build.bat
- azure-pipelines.yml
- recipe/meta.yaml
> Rebuild for EigenPy 3.10.1

- recipe/meta.yaml
- recipe/patches/0001-cmake-Use-IMPLIB-instead-of-LOCATION-on-Windows.patch
> Fix subpackage pinning and Windows support

- recipe/meta.yaml
- recipe/patches/0002-core-Fix-pragma-message-use-with-clang-cl.patch
> Fix build issue with clang-cl

- .gitignore
- recipe/meta.yaml
> Always be synchronize with coal
